version: '3'

services:
  db:
    image: mariadb
    container_name: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=235235
      - MYSQL_PASSWORD=235
    env_file:
      - ~/db.env

  app:
    build: ./docker/nextcloud
    container_name: nextcloud
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=235
    env_file:
      - ~/db.env
    depends_on:
      - db

  web:
    build: ./docker/web
    container_name: nginx
    restart: always
    volumes:
      - ./data/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.thesystem.at
      - LETSENCRYPT_HOST=cloud.thesystem.at
      - LETSENCRYPT_EMAIL=thesystemcollective@gmail.com
    depends_on:
      - app
    networks:
      - proxy-tier
      - default

  collabora:
    image: collabora/code
    container_name: collabora
    expose:
      - 9980
    cap_add:
      - MKNOD
    environment:
      - VIRTUAL_HOST=office.thesystem.at
      - LETSENCRYPT_HOST=office.thesystem.at
      - domain=office.thesystem.at
      - VIRTUAL_HOST=office.thesystem.at
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=9980
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_EMAIL=thesystemcollective@gmail.com
    networks:
      - proxy-tier

  proxy:
    build: ./docker/proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro    
    networks:
      - proxy-tier
    # depends_on:
    #   - nginx-proxy-letsencrypt

  certbot:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes_from: 
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro \
      - /etc/acme.sh 
    environment:
      - DEFAULT_EMAIL=thesystemcollective@gmail.com

volumes:
  db:
  nextcloud:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
